import { expect, test } from '@playwright/test';
import { watchConsole } from '../support/console';
import en from '@spec/en.json';

test.describe.serial('Contest Administration desktop — real Contest domain',()=>{
  let contestId='';let versionId='';let builder='';

  test('(AC-CA-NAV-01) Performance exposes Contest Administration',async({page})=>{
    const watch=watchConsole(page);await page.goto('/insights/performance');await page.getByRole('link',{name:'Contest administration'}).click();await expect(page).toHaveURL('/contest-admin/contests');await expect(page.getByRole('heading',{name:'Contest administration'})).toBeVisible();expect(watch.errors).toEqual([]);expect(watch.warnings).toEqual([]);
  });

  test('(AC-CA-HIST-UI-01) navigation exposes Historic contests and no Template screen',async({page})=>{const watch=watchConsole(page);await page.goto('/contest-admin/contests');await page.getByRole('link',{name:'Historic contests'}).click();await expect(page).toHaveURL('/contest-admin/historic-contests');await expect(page.getByRole('heading',{name:'Historic contests'})).toBeVisible();await expect(page.getByText(en['contest.state.empty'])).toBeVisible();await expect(page.getByRole('link',{name:'Templates'})).toHaveCount(0);expect(watch.errors).toEqual([]);});

  test('(AC-CA-AI-UI-01/02/03/04/05) brochure upload creates a reload-safe draft with English nested rules',async({page})=>{const watch=watchConsole(page);await page.goto('/contest-admin/contests');await page.getByRole('button',{name:'Create contest'}).click();const dialog=page.getByRole('dialog',{name:'Create contest'});await dialog.getByText('Create from brochure',{exact:true}).click();await dialog.getByLabel('Contest code').fill(`AI_UI_${Date.now()}`);await dialog.getByLabel('Contest brochure PDF').setInputFiles({name:'contest.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.7\nsynthetic contest brochure\n%%EOF')});await dialog.getByRole('button',{name:'Upload and create draft'}).click();await expect(page).toHaveURL(/\/contest-admin\/contest-imports\/contestimport_/);await page.reload();await expect(page.getByRole('heading',{name:'Creating contest from brochure'})).toBeVisible();await expect(page.getByText('Generated from brochure · Business review required')).toBeVisible({timeout:10000});await page.getByRole('link',{name:'Review draft'}).click();await expect(page).toHaveURL(/\/edit\/BASICS/);await expect(page.getByText('Business review required')).toBeVisible();await page.getByRole('link',{name:/Qualification/}).click();await page.getByRole('link',{name:'Edit rule'}).click();await expect(page.getByRole('heading',{name:'Rule logic in English'})).toBeVisible();await expect(page.getByText(/First Year Premium \/ Contribution must be greater than or equal to RM 25,000/)).toBeVisible();expect(watch.errors).toEqual([]);});

  test('(AC-CA-01) create contest navigates to the backend-created draft',async({page})=>{
    const watch=watchConsole(page);await page.goto('/contest-admin/contests');await page.getByRole('button',{name:'Create contest'}).click();const dialog=page.getByRole('dialog',{name:'Create contest'});await dialog.getByLabel('Contest name').fill('Malaysia Growth Challenge');await dialog.getByLabel('Contest code').fill('MY_GROWTH_UI');await dialog.getByRole('button',{name:'Create contest'}).click();
    await expect(page).toHaveURL(/\/contest-admin\/contests\/contest_[^/]+\/versions\/version_[^/]+\/edit\/BASICS/);const match=/contests\/([^/]+)\/versions\/([^/]+)/.exec(page.url())!;contestId=match[1]!;versionId=match[2]!;builder=`/contest-admin/contests/${contestId}/versions/${versionId}`;
    await expect(page.getByLabel('Contest code')).toHaveValue('MY_GROWTH_UI');expect(watch.errors).toEqual([]);
  });

  test('(AC-CA-01-01/02/03) portfolio searches backend data and opens row-owned route',async({page})=>{
    const watch=watchConsole(page);await page.goto('/contest-admin/contests');await page.getByPlaceholder('Search by name, code or owner').fill('MY_GROWTH_UI');await page.getByRole('button',{name:'Search'}).click();await expect(page).toHaveURL(/query=MY_GROWTH_UI/);await expect(page.getByText('MY_GROWTH_UI')).toBeVisible();await page.getByRole('link',{name:'Open'}).click();await expect(page).toHaveURL(new RegExp(`${contestId}/versions/${versionId}/edit/BASICS`));expect(watch.errors).toEqual([]);
  });

  test('(AC-CA-02, AC-CA-ROUTE-01/02) builder saves domain configuration and persists a nested route',async({page,request})=>{
    const current=await (await request.get(`/api/bff/v1/contest-admin/contests/${contestId}/versions/${versionId}`)).json();await request.patch(`/api/bff/v1/contest-admin/contests/${contestId}/versions/${versionId}`,{headers:{'If-Match':current.etag},data:{configuration:{basics:{code:'MY_GROWTH_UI',nameKey:'contest.created.new',country:'MY',timezone:'Asia/Kuala_Lumpur',name:'New contest'},audience:{codes:['PERSONAL']},calculation:{metricCode:'FYP',creditRate:'100.00'},rewards:{precedenceCode:'HIGHEST_ONLY'},governance:{frequencyCode:'DAILY'}}}});
    await page.goto(`${builder}/edit/QUALIFICATION`);await page.getByRole('button',{name:'Add route'}).click();const dialog=page.getByRole('dialog',{name:'Add qualification route'});await dialog.getByLabel('Route name').fill('Personal production gate');await dialog.getByLabel('Route code').fill('PERSONAL_GATE_UI');await dialog.getByLabel('Audience').selectOption('PERSONAL');await dialog.getByLabel('Any condition').check();await dialog.getByLabel('Tier code').fill('SILVER');await dialog.getByLabel('Reward code').fill('STAR_1');await dialog.getByRole('button',{name:'Add route'}).click();
    await expect(page).toHaveURL(/rules\/route_personal_gate_ui/);await expect(page.getByRole('heading',{name:'Rule logic in English'})).toBeVisible();await expect(page.getByRole('region',{name:/ANY/})).toBeVisible();await page.getByRole('button',{name:'Add condition'}).click();const condition=page.locator('.ca-predicate').first();await condition.getByLabel('Metric').selectOption('FYP');await condition.getByLabel('Target value').fill('25000.00');const explanation='First Year Premium / Contribution must be greater than or equal to RM 25,000.';await expect(page.getByText(explanation)).toBeVisible();await page.getByRole('button',{name:'Save rule'}).click();await expect(page.getByText('Rule saved')).toBeVisible();await page.reload();await expect(page.getByLabel('Target value').first()).toHaveValue('25000.00');await expect(page.getByText(explanation)).toBeVisible();
  });

  test('(AC-CA-04/07) review validates and submits the backend draft',async({page})=>{
    await page.goto(`${builder}/review`);await expect(page.getByRole('heading',{name:'Review and submit'})).toBeVisible();await expect(page.getByText('Pass',{exact:true})).toBeVisible();await page.getByRole('checkbox',{name:/confirm this version/i}).check();await page.getByRole('button',{name:'Submit for approval'}).click();await expect(page.getByText('Submitted',{exact:true})).toBeVisible();
    await page.goto('/contest-admin/approvals?inbox=ASSIGNED');await expect(page.getByRole('heading',{name:'New contest'}).first()).toBeVisible();
  });

  test('(AC-CA-08/05) audit and simulation screens show backend-owned state',async({page})=>{
    await page.goto('/contest-admin/audit');await expect(page.getByRole('heading',{name:'Audit log'})).toBeVisible();await expect(page.getByText('Contest created').first()).toBeVisible();await expect(page.getByRole('button',{name:'Export audit'})).toHaveCount(0);
    await page.goto(`${builder}/simulations`);await page.getByRole('button',{name:'Run simulation'}).click();await expect(page.getByText('Queued')).toBeVisible();await expect(page.locator('.ca-job code')).not.toBeEmpty();
  });

  test('(AC-CA-06-01/05) reusable rule creation, validation and save persist through backend',async({page})=>{
    const watch=watchConsole(page);await page.goto('/contest-admin/rules');await page.getByRole('button',{name:'New rule'}).click();const dialog=page.getByRole('dialog',{name:'Create reusable rule'});await dialog.getByLabel('Rule name').fill('High quality production');await dialog.getByLabel('Rule code').fill('HIGH_QUALITY_UI');await dialog.getByLabel('Rule category').selectOption('QUALITY');await dialog.getByLabel('Any condition').check();await dialog.getByRole('button',{name:'New rule'}).click();await expect(page).toHaveURL(/\/contest-admin\/rules\/rule_[^/]+\/versions\/ruleversion_/);await expect(page.getByText('This group has no conditions yet.')).toBeVisible();await page.getByRole('button',{name:'Add condition'}).click();const condition=page.locator('.ca-predicate').first();await condition.getByLabel('Metric').selectOption('FYP');await condition.getByLabel('Target value').fill('25000.00');await expect(page.getByText('First Year Premium / Contribution must be greater than or equal to RM 25,000.')).toBeVisible();await page.getByRole('button',{name:'Test rule'}).click();await expect(page.getByText(/rule nodes explained/)).toBeVisible();await page.getByRole('button',{name:'Save rule'}).click();await expect(page.getByText('Rule saved')).toBeVisible();await page.reload();await expect(page.getByLabel('Target value').first()).toHaveValue('25000.00');expect(watch.errors).toEqual([]);
  });
});