import type { ImportedCircularVM } from '@spec/contest-admin-vm';
import { t } from '@/lib/i18n';

const list = (values:string[]) => values.join(' · ');
const source = (ids:string[]) => ids.map(id => id.split(':').slice(0,2).join(' · ')).join(', ');

export function ImportedCircularPanel({ imported, section }:{imported:ImportedCircularVM;section:'AUDIENCE'|'QUALIFICATION'|'CALCULATION'|'REWARDS'|'GOVERNANCE'|'REVIEW'}) {
  if(section==='AUDIENCE') return <div className="ca-import-grid">{imported.audienceRules.map((rule,index)=><article key={`${rule.audienceCode}-${index}`}><header><strong>{t(`contest.audience.${rule.audienceCode}`)}</strong><span className={rule.include?'is-included':'is-excluded'}>{t(rule.include?'contest.import.included':'contest.import.excluded')}</span></header><p>{list(rule.rankCodes)}</p>{rule.entityCodes&&<small>{t('contest.import.entities',{values:list(rule.entityCodes)})}</small>}{rule.contractFrom&&<small>{t('contest.import.contractWindow',{from:rule.contractFrom,to:rule.contractTo??''})}</small>}{rule.maxAge&&<small>{t('contest.import.maxAge',{age:rule.maxAge})}</small>}<code>{source(rule.sourceCitationIds)}</code></article>)}</div>;
  if(section==='QUALIFICATION'||section==='REWARDS') return <div className="ca-import-rules">{imported.awardRules.map(rule=><article key={rule.ruleId}><header><div><strong>{t(rule.labelKey)}</strong><span>{t(`contest.audience.${rule.audienceCode}`)} · {list(rule.rankCodes)}</span></div>{rule.topN&&<b>{t('contest.import.topN',{count:rule.topN})}</b>}</header>{section==='QUALIFICATION'?<div className="ca-import-options">{rule.options.map(option=><section key={option.optionCode}><h4>{t('contest.import.option',{code:option.optionCode})}</h4>{option.allOf.length?<ul>{option.allOf.map((item,index)=><li key={`${item.metricCode}-${index}`}><strong>{item.metricCode}</strong><span>{item.operator} {item.value}{item.currency?` ${item.currency}`:''}</span>{item.periodId&&<small>{item.periodId}</small>}</li>)}</ul>:<p>{t('contest.import.rankingOnly')}</p>}</section>)}</div>:<p>{t('contest.import.rewards',{values:list(rule.rewardCodes)})}</p>}{rule.rankByMetricCode&&<footer>{t('contest.import.rankedBy',{metric:rule.rankByMetricCode,tie:rule.tieBreakMetricCode??t('contest.import.none')})}</footer>}<code>{source(rule.sourceCitationIds)}</code></article>)}</div>;
  if(section==='CALCULATION') return <div className="ca-import-grid">{imported.creditRules.map(rule=><article key={rule.ruleId}><header><strong>{rule.productCode}</strong><span className={rule.include?'is-included':'is-excluded'}>{t(rule.include?'contest.import.included':'contest.import.excluded')}</span></header><p>{rule.metricCode} · {t('contest.import.creditRate',{rate:rule.rate})}</p>{rule.capPctOfMetric&&<small>{t('contest.import.cap',{cap:rule.capPctOfMetric})}</small>}{rule.minimumSharePct&&<small>{t('contest.import.minimumShare',{share:rule.minimumSharePct})}</small>}<code>{source(rule.sourceCitationIds)}</code></article>)}</div>;
  if(section==='GOVERNANCE') return <div className="ca-import-grid">{imported.trackingRules.map(rule=><article key={rule.ruleId}><header><strong>{rule.type}</strong><span>{rule.effectiveTo}</span></header><p>{rule.actionCode}</p><code>{source(rule.sourceCitationIds)}</code></article>)}</div>;
  return <div className="ca-import-review"><header><div><span>{t('contest.import.effectiveCircular')}</span><strong>{imported.effectiveCircularCode}</strong></div><b>{t(`contest.import.reviewState.${imported.reviewState}`)}</b></header><p>{imported.sourceName}</p><h3>{t('contest.import.sourceHistory')}</h3><ol>{imported.citations.map(item=><li key={item.citationId}><span>{item.circularCode} · {t('contest.import.page',{page:item.page})} · {item.section}</span><strong>{t(`contest.import.citationStatus.${item.status}`)}</strong>{item.supersededBy&&<small>{t('contest.import.supersededBy',{code:item.supersededBy})}</small>}</li>)}</ol>{imported.exclusions.length>0&&<><h3>{t('contest.import.exclusions')}</h3><ul>{imported.exclusions.map(item=><li key={item.code}>{t(item.labelKey)}</li>)}</ul></>}</div>;
}