import { getLbuContext } from '@/config/lbu';
import type { ApprovalDecisionRequestVM, ApprovalDecisionResultVM, ApprovalInboxVM, ArchiveContestResultVM, AuditLogVM, ContestBuilderVM, ContestConfigurationVM, ContestImportVM, ContestPortfolioVM, ContestStatus, CreateContestRequestVM, CreateContestResultVM, CreateQualificationRouteRequestVM, HistoricContestLibraryVM, QualificationConfigurationVM, QualificationRouteVM, ReactivateContestRequestVM, ReactivateContestResultVM, ReviewVM, RuleEditorVM, RuleExpressionVM, RuleOptionsVM, SimulationVM, SimulationWorkspaceVM, StartSimulationRequestVM, SubmitContestRequestVM, SubmitContestResultVM, ValidationIssueVM } from '@spec/contest-admin-vm';
import { contestAdminConfig } from './config';
import { contestDomain, type ContestIdentity, type DomainApproval, type DomainContestSummary, type DomainContestVersion, type DomainSimulation, type DomainValidation } from './domain-client';
import { governedContestCatalogue } from './governed-catalogue';

const permissions=['contests:read','contests:write','contests:submit','contests:simulate','contests:audit:read'];
const meta=()=>({traceId:'contest-domain',generatedAt:new Date().toISOString(),permissions});
const summary=(item:DomainContestSummary):ContestPortfolioVM['contests'][number]=>({contestId:item.contestId,code:item.code,nameKey:item.nameKey,status:item.status as ContestStatus,ownerRef:item.ownerRef,campaignStart:item.campaignStart,campaignEnd:item.campaignEnd,audienceCodes:item.audienceCodes??[],ruleCount:item.ruleCount??0,updatedAt:item.updatedAt,nav:{route:`/contest-admin/contests/${item.contestId}/versions/${item.latestVersionId??''}/edit/BASICS`}});
const issue=(item:{path:string;code:string;severity:string;messageKey?:string},index:number):ValidationIssueVM=>({issueId:`validation_${index}`,severity:item.severity==='WARNING'?'WARNING':item.severity==='INFO'?'INFO':'ERROR',code:item.code,path:item.path,messageKey:item.messageKey??'contest.error.ruleInvalid',acknowledgementAllowed:false});
const validation=(report?:DomainValidation)=>({blocking:report?.status==='INVALID',issues:(report?.issues??[]).map(issue)});
const stepStatus=(configuration:Record<string,unknown>,step:string,report?:DomainValidation):ContestBuilderVM['steps'][number]['status']=>report?.issues.some(value=>value.path.toLowerCase().includes(step.toLowerCase()))?'ERROR':configuration[step.toLowerCase()]&&Object.keys(configuration[step.toLowerCase()] as object).length?'VALID':'NOT_STARTED';

export async function portfolio(query:URLSearchParams,identity?:ContestIdentity):Promise<ContestPortfolioVM>{const params=new URLSearchParams();for(const key of ['query','status','cursor','limit']){const value=query.get(key);if(value)params.set(key,value);}const suffix=params.size?`?${params}`:'';const [{body:list},{body:overview}]=await Promise.all([contestDomain.listContests(suffix,identity),contestDomain.overview(identity)]);const details=await Promise.all(list.items.map(item=>contestDomain.getContest(item.contestId,identity).then(value=>value.body)));return{meta:meta(),metrics:overview.metrics.map(value=>({...value,code:value.code==='TOTAL'?'TOTAL_CONTESTS':value.code})),attentionItems:overview.attentionItems.map(value=>({...value,nav:{route:'/contest-admin/approvals'}})),contests:details.map(summary),page:list.page,filters:{statuses:['DRAFT','IN_REVIEW','ACTIVE','COMPLETED'],cycles:[],entityCodes:[],channelCodes:[]}};}
export async function createContest(input:CreateContestRequestVM,key:string,identity?:ContestIdentity):Promise<CreateContestResultVM>{const {body}=await contestDomain.createContest(input,key,identity);return{...summary(body),country:body.country??getLbuContext().country,timezone:body.timezone??input.timezone,latestVersionId:body.latestVersionId!};}
export async function contestImport(importId:string,identity?:ContestIdentity):Promise<ContestImportVM>{const {body}=await contestDomain.getContestImport(importId,identity);const value=body as unknown as Omit<ContestImportVM,'meta'>;return{...value,meta:meta(),brochure:{...value.brochure,...(value.result?{downloadNav:{route:`/api/bff/v1/contest-admin/contests/${value.result.contestId}/versions/${value.result.versionId}/brochure`}}:{})},...(value.result?{result:{...value.result,nav:{route:`/contest-admin/contests/${value.result.contestId}/versions/${value.result.versionId}/edit/BASICS`}}}:{})};}
export async function builder(contestId:string,versionId:string,identity?:ContestIdentity,report?:DomainValidation):Promise<ContestBuilderVM>{const [{body:contest},{body:version,etag}]=await Promise.all([contestDomain.getContest(contestId,identity),contestDomain.getContestVersion(versionId,identity)]);if(version.contestId!==contestId)throw new Error('Contest version does not belong to contest');const configuration={...version.configuration,qualification:qualification(version)} as ContestConfigurationVM;return{meta:meta(),contest:summary({...contest,latestVersionId:versionId}),versionId,revision:version.revision,etag:etag??`"${version.revision}"`,readOnly:version.status!=='DRAFT',steps:contestAdminConfig.builder.stepOrder.map(stepCode=>({stepCode,status:stepStatus(configuration,stepCode,report),issueCount:report?.issues.filter(value=>value.path.toLowerCase().includes(stepCode.toLowerCase())).length??0,nav:{route:`/contest-admin/contests/${contestId}/versions/${versionId}/edit/${stepCode}`}})),activeStep:'BASICS',configuration,catalogue:governedContestCatalogue,...(version.brochure?{brochure:{...version.brochure,downloadNav:{route:`/api/bff/v1/contest-admin/contests/${contestId}/versions/${versionId}/brochure`}}}:{}),validation:validation(report),autosave:{state:'SAVED',...(version.updatedAt?{savedAt:version.updatedAt}:{})}};}
export async function patchBuilder(contestId:string,versionId:string,configuration:Record<string,unknown>,etag:string,identity?:ContestIdentity):Promise<ContestBuilderVM>{await contestDomain.patchContestVersion(versionId,configuration,etag,identity);return builder(contestId,versionId,identity);}
export async function review(contestId:string,versionId:string,identity?:ContestIdentity):Promise<ReviewVM>{const [{body:version},{body:contest},{body:report}]=await Promise.all([contestDomain.getContestVersion(versionId,identity),contestDomain.getContest(contestId,identity),contestDomain.validateContestVersion(versionId,crypto.randomUUID(),identity)]);return{meta:meta(),contest:summary({...contest,latestVersionId:versionId}),versionId,checksum:version.checksum,sections:contestAdminConfig.builder.stepOrder.filter(value=>value!=='REVIEW').map(stepCode=>({stepCode,status:stepStatus(version.configuration,stepCode,report),summaryKeys:[],editNav:{route:`/contest-admin/contests/${contestId}/versions/${versionId}/edit/${stepCode}`}})),changes:[],validation:validation(report),approvalStages:[{stageId:'BUSINESS',order:1,type:'BUSINESS',status:'PENDING'}]};}
const approvalVM=async(item:DomainApproval,identity?:ContestIdentity)=>{const contest=await contestDomain.getContest(item.contestId,identity);return{approvalId:item.approvalId,contest:summary({...contest.body,latestVersionId:item.versionId}),versionId:item.versionId,snapshotChecksum:item.snapshotChecksum,status:item.status,submittedBy:item.submittedBy,submittedAt:item.submittedAt,materialChanges:0,actions:['OPEN','APPROVE','RETURN','REJECT'] as Array<'OPEN'|'APPROVE'|'RETURN'|'REJECT'>,nav:{route:`/contest-admin/contests/${item.contestId}/versions/${item.versionId}/review`}};};
export async function approvals(inbox:string|undefined,identity?:ContestIdentity):Promise<ApprovalInboxVM>{const selected=(['ASSIGNED','SUBMITTED','COMPLETED'].includes(inbox??'')?inbox:'ASSIGNED') as ApprovalInboxVM['inbox'];const status=selected==='COMPLETED'?'APPROVED':undefined;const {body}=await contestDomain.listApprovals(status,identity);return{meta:meta(),inbox:selected,counts:{[selected]:body.items.length},items:await Promise.all(body.items.map(item=>approvalVM(item,identity))),page:body.page};}
export async function decide(approvalId:string,input:ApprovalDecisionRequestVM,etag:string,key:string,identity?:ContestIdentity):Promise<ApprovalDecisionResultVM>{const {body}=await contestDomain.decideApproval(approvalId,input,etag,key,identity);return{approvalId,status:(body.status==='RETURNED'?'RETURNED':body.status==='REJECTED'?'REJECTED':'APPROVED'),decidedAt:body.decidedAt??new Date().toISOString(),...(body.returnedVersionId?{editableDraftNav:{route:`/contest-admin/contests/${body.contestId}/versions/${body.returnedVersionId}/edit/BASICS`}}:{})};}
export async function historicContests(query:URLSearchParams,identity?:ContestIdentity):Promise<HistoricContestLibraryVM>{const params=new URLSearchParams();for(const key of ['query','status','cursor','limit']){const value=query.get(key);if(value)params.set(key,value);}const {body}=await contestDomain.listHistoric(params.size?`?${params}`:'',identity);return{meta:meta(),items:body.items.map(item=>({...item,nav:{route:`/contest-admin/contests/${item.contestId}/versions/${item.latestVersionId}/review`},brochure:item.brochure?{...item.brochure,downloadNav:{route:`/api/bff/v1/contest-admin/contests/${item.contestId}/versions/${item.latestVersionId}/brochure`}}:undefined})),page:body.page,filters:{statuses:['COMPLETED','CANCELLED','ARCHIVED']}};}
export async function archive(contestId:string,etag:string,key:string,identity?:ContestIdentity):Promise<ArchiveContestResultVM>{return (await contestDomain.archiveContest(contestId,etag,key,identity)).body;}
export async function reactivate(contestId:string,input:ReactivateContestRequestVM,etag:string,key:string,identity?:ContestIdentity):Promise<ReactivateContestResultVM>{const {body}=await contestDomain.reactivateContest(contestId,input,etag,key,identity);return{contestId,versionId:body.versionId,revision:body.revision,status:'DRAFT',baseVersionId:body.baseVersionId!,baseChecksum:(body as DomainContestVersion&{baseChecksum:string}).baseChecksum,nav:{route:`/contest-admin/contests/${contestId}/versions/${body.versionId}/edit/BASICS`}};}
export async function audit(identity?:ContestIdentity):Promise<AuditLogVM>{const {body}=await contestDomain.listAudit(identity);return{meta:meta(),items:body.items.map(item=>({...item,...(item.versionId?{detailNav:{route:`/contest-admin/contests/${item.resourceId}/versions/${item.versionId}/review`}}:{})})),page:body.page};}
const simulations=new Map<string,string>();
const simulationVM=(contestId:string,versionId:string,value?:DomainSimulation):SimulationWorkspaceVM=>({meta:meta(),contestId,versionId,allowedTypes:['SAMPLE_PARTICIPANT','PORTFOLIO_IMPACT'],...(value?{simulation:{jobId:value.jobId,status:value.status as SimulationVM['status'],progressPct:value.progressPct,type:value.simulationType,summary:value.reconciliation,problemCode:value.problemCode}}:{})});
export async function startSimulation(contestId:string,versionId:string,input:StartSimulationRequestVM,key:string,identity?:ContestIdentity){const {body}=await contestDomain.startSimulation(versionId,input,key,identity);simulations.set(`${identity?.tenant??'MY'}:${contestId}:${versionId}`,body.simulationId);return simulationVM(contestId,versionId,body);}
export async function pollSimulation(contestId:string,versionId:string,identity?:ContestIdentity){const simulationId=simulations.get(`${identity?.tenant??'MY'}:${contestId}:${versionId}`);if(!simulationId)return simulationVM(contestId,versionId);const {body}=await contestDomain.getSimulation(simulationId,identity);return simulationVM(contestId,versionId,body);}
export async function submit(versionId:string,input:SubmitContestRequestVM,etag:string,key:string,identity?:ContestIdentity):Promise<SubmitContestResultVM>{const {body}=await contestDomain.submitContestVersion(versionId,input,etag,key,identity);return{approvalId:body.approvalId,versionId:body.versionId,snapshotChecksum:body.snapshotChecksum,status:'IN_PROGRESS',nav:{route:'/contest-admin/approvals?inbox=SUBMITTED'}};}

const qualification=(version:DomainContestVersion):QualificationConfigurationVM=>{
  const value=(version.configuration.qualification??{}) as Partial<QualificationConfigurationVM>;
  return{routes:value.routes??[],tiers:value.tiers??[],periods:value.periods??[],targets:value.targets??[],rewardPrecedenceCode:value.rewardPrecedenceCode??'HIGHEST_ONLY'};
};
const routeEditor=(contestId:string,version:DomainContestVersion,route:QualificationRouteVM,etag?:string,report?:DomainValidation):RuleEditorVM=>({meta:meta(),contestId,versionId:version.versionId,ruleId:route.routeId,categoryCode:route.audienceCode??'ELIGIBILITY',tierCode:route.tierIds[0]??'NOT_APPLICABLE',expression:route.expression,options:{periodMode:'FULL_CAMPAIGN',unknownCodePolicy:'BLOCK'},catalogue:governedContestCatalogue,limits:{maxDepth:contestAdminConfig.builder.maxRuleDepth,maxNodes:contestAdminConfig.builder.maxRuleNodes},issues:(report?.issues??[]).map(issue),etag:etag??`"${version.revision}"`,readOnly:version.status!=='DRAFT',editorContext:'CONTEST_VERSION',cancelNav:{route:`/contest-admin/contests/${contestId}/versions/${version.versionId}/edit/QUALIFICATION`}});
export async function createQualificationRoute(contestId:string,versionId:string,input:CreateQualificationRouteRequestVM,identity?:ContestIdentity):Promise<QualificationRouteVM>{const {body:version}=await contestDomain.getContestVersion(versionId,identity);if(version.contestId!==contestId)throw new Error('Contest version does not belong to contest');const current=qualification(version);const routeId=`route_${input.code.toLowerCase().replaceAll(/[^a-z0-9]+/g,'_')}`;const created:QualificationRouteVM={routeId,code:input.code,labelKey:`contest.route.${input.code}`,name:input.name,order:current.routes.length+1,enabled:true,audienceCode:input.audienceCode,expression:{nodeId:`root_${routeId}`,type:input.rootType,children:[]},tierIds:[input.tierCode],rewardPolicy:{rewardCodes:[input.rewardCode],precedenceCode:'HIGHEST_ONLY'}};await contestDomain.patchContestVersion(versionId,{qualification:{...current,routes:[...current.routes,created]}},input.etag,identity);return created;}
export async function getEmbeddedRule(contestId:string,versionId:string,ruleId:string,identity?:ContestIdentity):Promise<RuleEditorVM>{const {body,etag}=await contestDomain.getContestVersion(versionId,identity);if(body.contestId!==contestId)throw new Error('Contest version does not belong to contest');const route=qualification(body).routes.find(item=>item.routeId===ruleId);if(!route)throw new Error('Qualification route not found');return routeEditor(contestId,body,route,etag);}
export async function saveEmbeddedRule(contestId:string,versionId:string,ruleId:string,input:{expression:RuleExpressionVM;options:RuleOptionsVM;etag:string},identity?:ContestIdentity):Promise<RuleEditorVM>{const {body:version}=await contestDomain.getContestVersion(versionId,identity);if(version.contestId!==contestId)throw new Error('Contest version does not belong to contest');const current=qualification(version);const index=current.routes.findIndex(item=>item.routeId===ruleId);if(index<0)throw new Error('Qualification route not found');const route={...current.routes[index]!,expression:input.expression};const routes=[...current.routes];routes[index]=route;const saved=await contestDomain.patchContestVersion(versionId,{qualification:{...current,routes}},input.etag,identity);return routeEditor(contestId,saved.body,route,saved.etag);}
export async function testEmbeddedRule(contestId:string,versionId:string,ruleId:string,input:{expression:RuleExpressionVM;options:RuleOptionsVM},identity?:ContestIdentity):Promise<RuleEditorVM>{const [{body:version,etag},{body:report}]=await Promise.all([contestDomain.getContestVersion(versionId,identity),contestDomain.validateContestVersion(versionId,crypto.randomUUID(),identity)]);const route=qualification(version).routes.find(item=>item.routeId===ruleId);if(!route)throw new Error('Qualification route not found');return routeEditor(contestId,version,{...route,expression:input.expression},etag,report);}