import type { CreateRuleAssetRequestVM, CreateRuleAssetResultVM, RuleEditorVM, RuleExpressionVM, RuleLibraryVM, RuleOptionsVM, ValidationIssueVM } from '@spec/contest-admin-vm';
import { contestAdminConfig } from './config';
import { contestDomain, type ContestIdentity, type DomainRuleReport, type DomainRuleSummary, type DomainRuleVersion } from './domain-client';
import { governedContestCatalogue } from './governed-catalogue';

const meta={traceId:'contest-domain',generatedAt:new Date().toISOString(),permissions:['contests:read','contests:rules:write']};
const nav=(assetId:string,versionId:string)=>({route:`/contest-admin/rules/${assetId}/versions/${versionId}`});
const issue=(value:{path:string;code:string;messageKey?:string},index:number):ValidationIssueVM=>({issueId:`domain_${index}`,path:value.path,code:value.code,messageKey:value.messageKey??messageKey(value.code),severity:'ERROR',acknowledgementAllowed:false});
const messageKey=(code:string)=>({UNKNOWN_METRIC:'contest.error.unknownMetric',INVALID_OPERATOR:'contest.error.invalidOperator',INVALID_OPERAND:'contest.error.invalidOperand',EMPTY_GROUP:'contest.error.emptyGroup',DUPLICATE_NODE_ID:'contest.error.duplicateNodeId',RULE_DEPTH_LIMIT:'contest.error.ruleDepth',RULE_NODE_LIMIT:'contest.error.ruleLimit'}[code]??'contest.error.ruleInvalid');
const root=(code:string,type:'ALL'|'ANY'):RuleExpressionVM=>({nodeId:`root_${code.toLowerCase().replaceAll(/[^a-z0-9]+/g,'_').slice(0,40)}`,type,children:[]});
const domainCatalogue=governedContestCatalogue;
const summary=(item:DomainRuleSummary)=>({assetId:item.assetId,code:item.code,name:item.name,type:'RULE' as const,categoryCode:item.categoryCode,status:item.status,latestVersion:item.latestVersion,latestVersionId:item.latestVersionId,adoptionCount:item.adoptionCount,nav:nav(item.assetId,item.latestVersionId)});
export async function listRules(identity?:ContestIdentity):Promise<RuleLibraryVM>{const {body}=await contestDomain.listRules(identity);return{meta:{...meta,generatedAt:new Date().toISOString()},items:body.items.map(summary),filters:{categoryCodes:['ELIGIBILITY','QUALITY','PRODUCTION'],statuses:['DRAFT','IN_REVIEW','APPROVED']}};}
export async function createRule(request:CreateRuleAssetRequestVM,key:string,identity?:ContestIdentity):Promise<CreateRuleAssetResultVM>{const {body}=await contestDomain.createRule({code:request.code,name:request.name,categoryCode:request.categoryCode,configuration:root(request.code,request.rootType)},key,identity);return{...summary(body),type:'RULE',status:'DRAFT',rootType:request.rootType,latestVersionId:body.latestVersionId};}
export async function getRuleEditor(assetId:string,versionId:string,identity?:ContestIdentity):Promise<RuleEditorVM>{const {body,etag}=await contestDomain.getRuleVersion(versionId,identity);if(body.assetId!==assetId)throw new Error('Rule version does not belong to the requested asset');return composeEditor(body,etag);}
function composeEditor(body:DomainRuleVersion,etag?:string,report?:DomainRuleReport):RuleEditorVM{return{meta:{...meta,generatedAt:new Date().toISOString()},contestId:'RULE_LIBRARY',versionId:body.ruleVersionId,ruleId:body.assetId,categoryCode:body.categoryCode,tierCode:'NOT_APPLICABLE',expression:body.expression,options:body.options,catalogue:domainCatalogue,limits:{maxDepth:contestAdminConfig.builder.maxRuleDepth,maxNodes:contestAdminConfig.builder.maxRuleNodes},issues:(report?.issues??[]).map(issue),etag:etag??`"${body.revision}"`,readOnly:body.status!=='DRAFT',editorContext:'REUSABLE_RULE',displayName:body.name,cancelNav:{route:'/contest-admin/rules'},...(report?{testResult:{qualificationStatus:report.valid?'QUALIFIED':'NOT_QUALIFIED',metrics:[],nodeResults:report.nodeOutcomes.map(item=>({nodeId:item.nodeId,passed:item.outcome==='PASS'?true:item.outcome==='FAIL'?false:undefined,errorCode:item.reasonCode})),configurationChecksum:report.configurationChecksum,engineVersion:report.engineVersion}}:{})};}
export async function saveRule(assetId:string,versionId:string,input:{expression:RuleExpressionVM;options:RuleOptionsVM;etag:string},key:string,identity?:ContestIdentity):Promise<RuleEditorVM>{const {body,etag}=await contestDomain.patchRuleVersion(versionId,{expression:input.expression,options:input.options},input.etag,key,identity);if(body.assetId!==assetId)throw new Error('Rule version does not belong to the requested asset');return composeEditor(body,etag);}
export async function testRule(assetId:string,versionId:string,input:{expression:RuleExpressionVM;options:RuleOptionsVM},key:string,identity?:ContestIdentity):Promise<RuleEditorVM>{const [{body:version,etag},{body:report}]=await Promise.all([contestDomain.getRuleVersion(versionId,identity),contestDomain.validateRuleVersion(versionId,input,key,identity)]);if(version.assetId!==assetId)throw new Error('Rule version does not belong to the requested asset');return composeEditor({...version,expression:input.expression,options:input.options},etag,report);}